import javax.swing.JOptionPane;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
             _  _       _           ___           _ ____      
            | || |     | |         / _ \         | |___ \     
  _   _ _ __| || |_ ___| | ___ __ | | | |_      _| | __) |___ 
 | | | | '_ \__   _/ __| |/ / '_ \| | | \ \ /\ / / ||__ <_  / 
 | |_| | | | | | || (__|   <| | | | |_| |\ V  V /| |___) / /  
  \__,_|_| |_| |_| \___|_|\_\_| |_|\___/  \_/\_/ |_|____/___| 
                                                              
                                                              
https://fuxkuhrz.wordpress.com/
https://www.facebook.com/PsynoxzhioQ
https://www.youtube.com/channel/UCNrT38ApdFrVMHjeEBu1MmQ/
https://twitter.com/_Fuxkuhrz_
*/

/**
 *
 * @author NETMONSTERZ
 */
public class GuessingGame extends javax.swing.JFrame {

    /**
     * Creates new form GuessingGame
     */
    
    int lives=15;
    int win_flag = 0;
    int GuessedNum = GuessingCore.Guessing();
    String GuessPayload;
    
    
    public GuessingGame() {
        initComponents();
        this.setTitle("Number Guessing Game by Un4ckn0wl3z [ Anuwat ]");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ตัวเลขจะอยู่ระหว่าง 0 - 999");

        jButton1.setText("คลิก!!! เพื่อสุ่ม");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("คุณสามารถสุ่มได้อีก");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("15");

        jLabel4.setText("ครั้ง");

        jLabel5.setText("เดี๋ยวฉันจะใบ้คำตอบให้คุณน่ะ :)");

        jButton2.setText("เริ่มใหม่");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("ค่าที่คุณป้อน :");

        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("ยังไม่ได้ป้อน");

        jLabel10.setText("[ ]");

        jLabel8.setText("แต้มที่ได้ : ");

        jLabel9.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel10)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(lives > 0){
        GuessPayload = jTextField1.getText();
        if(GuessPayload.equals("")){
            jLabel5.setText("คุณยังไม่ได้ป้อนตัวเลข กรุณาป้อนด้วยน่ะ :( ");
            JOptionPane.showMessageDialog(null,"คุณยังไม่ได้ป้อนตัวเลข กรุณาป้อนด้วยน่ะ :( ","คำเตือน",JOptionPane.WARNING_MESSAGE);
            
        }else if(Integer.parseInt(GuessPayload) >= 1000){
            jLabel5.setText("กรุณาป้อนค่าให้น้อยกว่า 1000 ด้วย น่ะ :p ");
            JOptionPane.showMessageDialog(null,"กรุณาป้อนค่าให้น้อยกว่า 1000 ด้วย น่ะ :p ","คำเตือน",JOptionPane.WARNING_MESSAGE);
        
        }
        
        
        else{
            if(String.valueOf(win_flag).equals("0")){
            lives--;
            jLabel3.setText(String.valueOf(lives));
            }
            System.out.println(GuessedNum);
            jLabel9.setText(String.valueOf(100*lives/15));
            System.out.println(jTextField1.getText());
            jLabel7.setText(GuessPayload);
            if(Integer.parseInt(GuessPayload) == GuessedNum){
                jLabel10.setText("[✓]");
                jLabel5.setText("ว้าววววว คุณสุ่มเจอจนได้ ยินดีด้วยจ้าาาาาา ^_^ ");
                JOptionPane.showMessageDialog(null,"ว้าววววว คุณสุ่มเจอจนได้ ยินดีด้วยจ้าาาาาา ^_^ ","คำเตือน",JOptionPane.WARNING_MESSAGE);
                win_flag = 1;
            }else if(Integer.parseInt(GuessPayload) > GuessedNum){
                jLabel5.setText("ตัวเลขสูงเกินไป โปรดลงค่าลงนิดนึง อิอิ :) ");
                jLabel10.setText("[✘]");
            }else if(Integer.parseInt(GuessPayload) < GuessedNum){
                jLabel5.setText("ตัวเลขน้อยไปอ่ะ เพิ่มค่าขึ้นหน่อยสิ :( ");
                jLabel10.setText("[✘]");
            }else{
                jLabel5.setText("ชั้นคิดว่าคงมีอะไรผิดพลาด :( ");
                jLabel10.setText("[✘]");
            }
            
        }
        }else{
            jLabel5.setText("เสียใจด้วย คุณแพ้แล้วว T^T");
            jLabel10.setText("[✘]");
            JOptionPane.showMessageDialog(null,"เสียใจด้วย คุณแพ้แล้วว T^T","คำเตือน",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        lives=15;
        jLabel3.setText("15");
        GuessedNum = GuessingCore.Guessing();
        win_flag = 0;
        jLabel7.setText("ยังไม่ได้ป้อน");
        jLabel10.setText("[ ]");
        jLabel9.setText("0");
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
